# This jobs are only used for gateway service

####################################################################
# Refer to http://docs.shippable.com/reference/jobs-overview/      #
# Resources are located in shippable.resources.yml file            #
# Jobs are numbered to visualize sequence                          #
####################################################################

jobs:
  # 1. Sync pipeline to CI
  - name: gateway-service_runCI
    type: runCI
    steps:
      - OUT: gateway-service-master-docker-registry

  # 2. Manifest for MASTER image
  - name: gateway-service-man-master
    type: manifest
    steps:
      - IN: gateway-service-master-docker-registry
      - IN: gateway-service-docker-opts
      - TASK: managed

  # 3. SIT deployment for MASTER
  - name: gateway-service-sit-deploy-master
    type: deploy
    always:
      - NOTIFY: gateway-service-slack-notifications
    steps:
      - IN: gateway-service-man-master # for master - auto deploy to SIT
        force: true
        switch: on
      - IN: gateway-service-sit-ecs
      - IN: gateway-service-sit-params
      - IN: gateway-service-sit-alb
        applyTo:
          - manifest: gateway-service-man-master
            image: gateway-service-master-docker-registry
            port: 3000
      - TASK: managed
        deployMethod: replace

  # 5. Package release for production release
  - name: gateway-service-package-master
    type: release
    steps:
      - IN: gateway-service-man-master
        force: true
        switch: off
      - IN: gateway-service-sit-deploy-master
      - IN: gateway-service-version
      - TASK: managed
        bump: minor
    on_success:
      - NOTIFY: gateway-service-deployment-notifications

  # 6. PROD deployment for MASTER
  - name: gateway-service-prod-deploy-master
    type: deploy
    always:
      - NOTIFY: gateway-service-slack-notifications
      - NOTIFY: gateway-service-deployment-notifications
    steps:
      - IN: gateway-service-package-master
        switch: off
      - IN: gateway-service-man-master
        force: true
      - IN: gateway-service-prod-ecs
      - IN: gateway-service-prod-params
      - IN: gateway-service-prod-alb
        applyTo:
          - manifest: gateway-service-man-master
            image: gateway-service-master-docker-registry
            port: 3000
      - TASK: managed
        deployMethod: upgrade
